### ISSUE TITLE
Need help for reconstracting your experiments

### ISSUE THREAD

**Issue by wenhaowang1995** [IcarusWizard/MAE#13]
Hi !
I install all the requirments by pip and when I run MAE code, here comes up with an error:

Traceback (most recent call last):\
File "D:\\mywork\\Projects\\PJ1\\my_MAE_cifar\\main.py", line 87, in \<module\>
rep, backward_indices = encoder(img0)
File "D:\\Python\\lib\\site-packages\\torch\\nn\\modules\\module.py", line 1110, in \_call_impl
return forward_call(\*input, \*\*kwargs)
File "D:\\mywork\\Projects\\PJ1\\my_MAE_cifar\\model.py", line 80, in forward
features = self.layer_norm(self.transformer(patches))
File "D:\\Python\\lib\\site-packages\\torch\\nn\\modules\\module.py", line 1110, in \_call_impl
return forward_call(\*input, \*\*kwargs)
File "D:\\Python\\lib\\site-packages\\torch\\nn\\modules\\container.py", line 141, in forward
input = module(input)
File "D:\\Python\\lib\\site-packages\\torch\\nn\\modules\\module.py", line 1110, in \_call_impl
return forward_call(\*input, \*\*kwargs)
File "D:\\Python\\lib\\site-packages\\timm\\models\\vision_transformer.py", line 268, in forward
x = x + self.drop_path1(self.ls1(self.attn(self.norm1(x))))
File "D:\\Python\\lib\\site-packages\\torch\\nn\\modules\\module.py", line 1185, in __getattr__
raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Block' object has no attribute 'drop_path1'. Did you mean: 'drop_path'?

This seems to be a problem comes from TIMM package

While I look into the vision_transformer.py ![image](https://user-images.githubusercontent.com/129756862/235351996-77ccc5e5-8507-42b3-b803-93f41f59c8ab.png) of TIMM package, it seems there is no problem with the drop_path1 and drop_path2.

Therefore could you please tell me which version of TIMM are you using? It is best if you could provide your torch and cuda version

**Comment by IcarusWizard** [comment]
Hi. The [requirement file](https://github.com/IcarusWizard/MAE/blob/main/requirements.txt) should already fix the `timm` to `0.4.21`. Could you check whether the version is correct by running `pip list`?

**Comment by wenhaowang1995** [comment]
Oh, really thanks, I use an environment with higher edition timm and torch, therefore, it directly ignore the previous edition. I create new env and install the requirements. The problems solved. 
Thank you very much. 
All the best
